export const GET_CURRENCY_RATE = 'GET_CURRENCY_RATE';
export const GET_CURRENCY_RATE_SUCCESS = 'GET_CURRENCY_RATE_SUCCESS';
export const GET_CURRENCY_RATE_FAILURE = 'GET_CURRENCY_RATE_FAILURE';

export const GET_HISTORICAL_CURRENCY_RATE = 'GET_HISTORICAL_CURRENCY_RATE'
export const GET_HISTORICAL_CURRENCY_RATE_SUCCESS = 'GET_HISTORICAL_CURRENCY_RATE_SUCCESS'
export const GET_HISTORICAL_CURRENCY_RATE_FAILURE = 'GET_HISTORICAL_CURRENCY_RATE_FAILURE'